# Generated by Django 3.0.6 on 2020-06-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=5, verbose_name='Температура')),
                ('icon', models.CharField(max_length=5, verbose_name='Иконка')),
                ('coord_lon', models.CharField(max_length=5, verbose_name='Долгота')),
                ('coord_lat', models.CharField(max_length=5, verbose_name='Широта')),
                ('sky', models.CharField(max_length=5, verbose_name='Облачность')),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=5, verbose_name='Температура')),
                ('time', models.CharField(max_length=15, verbose_name='Время')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=5, verbose_name='Температура')),
                ('time', models.CharField(max_length=15, verbose_name='Время')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
    ]
