# Generated by Django 3.0.6 on 2020-06-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.City'),
        ),
        migrations.AlterField(
            model_name='information',
            name='coord_lat',
            field=models.CharField(max_length=5, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='information',
            name='coord_lon',
            field=models.CharField(max_length=5, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='information',
            name='icon',
            field=models.CharField(max_length=5, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='information',
            name='sky',
            field=models.CharField(max_length=5, null=True, verbose_name='Облачность'),
        ),
        migrations.AlterField(
            model_name='information',
            name='temperature',
            field=models.CharField(max_length=5, null=True, verbose_name='Температура'),
        ),
    ]
