# Generated by Django 3.0.6 on 2020-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200601_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='country',
            field=models.CharField(max_length=5, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='information',
            name='humidity',
            field=models.CharField(max_length=5, null=True, verbose_name='Влажность'),
        ),
        migrations.AddField(
            model_name='information',
            name='pressure',
            field=models.CharField(max_length=5, null=True, verbose_name='Давление'),
        ),
        migrations.AddField(
            model_name='information',
            name='speed',
            field=models.CharField(max_length=5, null=True, verbose_name='Скорость ветра'),
        ),
        migrations.AddField(
            model_name='information',
            name='temp_max',
            field=models.CharField(max_length=5, null=True, verbose_name='Максимальная температура'),
        ),
        migrations.AddField(
            model_name='information',
            name='temp_min',
            field=models.CharField(max_length=5, null=True, verbose_name='Минимальная температура'),
        ),
        migrations.AddField(
            model_name='information',
            name='visibility',
            field=models.CharField(max_length=5, null=True, verbose_name='Влажность'),
        ),
    ]
