# Generated by Django 3.0.6 on 2020-06-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200604_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='feels_like',
            field=models.CharField(max_length=5, null=True, verbose_name='Чувствуется как'),
        ),
        migrations.AddField(
            model_name='information',
            name='sunrise',
            field=models.CharField(max_length=5, null=True, verbose_name='Восход'),
        ),
        migrations.AddField(
            model_name='information',
            name='sunset',
            field=models.CharField(max_length=5, null=True, verbose_name='Закат'),
        ),
        migrations.AddField(
            model_name='information',
            name='time',
            field=models.CharField(max_length=5, null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='information',
            name='visibility',
            field=models.CharField(max_length=5, null=True, verbose_name='Видимость'),
        ),
    ]
