# Generated by Django 3.0.6 on 2020-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200604_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='city',
        ),
        migrations.RemoveField(
            model_name='information',
            name='visibility',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
